### ISSUE TITLE
Max frame length of 65536 has been exceeded

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#6] opened 2016-04-03 19:42 UTC
I am trying to send out a largish text message from the server. I put an array of text  (array.toString()) in to the data object of the websocket message. The size of the array is about 3.6 MB. I increased this setting:
WEBSOCKET_MAX_MSG_SIZE=10000000

What else do I need to change?

**Comment by mwambler** [comment] 2016-04-03 21:18
Post this to github.  I think I know what the issue is.  I'll have a look
tomorrow.

On Sunday, April 3, 2016, Csaba Kiss <notifications@github.com> wrote:

> I am trying to send out a largish text message from the server. I put an
> array of text (array.toString()) in to the data object of the websocket
> message. The size of the array is about 3.6 MB. I increased this setting:
> WEBSOCKET_MAX_MSG_SIZE=10000000
>
> What else do I need to change?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/6>
>


-- 
Mark Ambler

**Comment by csakis** [comment] 2016-04-03 21:52
Ahemm, I just did. :)

**Comment by mwambler** [comment] 2016-04-06 12:22
xockets.2.0.3 up.  Updated embedded javascript client registration to override the default size and use the server's WEBSOCKET_MAX_MSG_SIZE parameter.

**Comment by mwambler** [comment] 2016-04-12 16:20
This should be fixed with the last release.  Are you able to confirm?

**Comment by csakis** [comment] 2016-04-12 16:53
I am sorry, I have not had time to test this yet.

**Comment by csakis** [comment] 2016-04-14 16:17
I am getting some new errors now. I am trying to build a big message from a view with 10000 records. Here is the server side code:
```
function onOpen(){
	print("we are open");
	var db = session.getDatabase("","RepeatTest.nsf");
	var usersView = db.getView("chats");
	var documents = usersView.getAllEntries();
	print("document length: " + documents.getCount());
	var result = new java.util.HashMap();
	var i=0;
	var entry = documents.getFirstEntry();
	while (entry != null)  {
	   var entryObject =new java.util.HashMap();
	   entryObject.put("author", entry.getDocument().getItemValueString("author"));
	   entryObject.put("chat", entry.getDocument().getItemValueString("chat"));
	//   entryObject.put("created", entry.getDocument().getItemValueString("created"));
	   result.put(i.toString(), entryObject);
	   var tmpentry = documents.getNextEntry();
	   entry.recycle();
	   entry=tmpentry;
	   i++;   
	}
	var serverMessage = websocketClient.createMessage();
	serverMessage.setTo("broadcast"); //respond to everybody
	serverMessage.setText("chat");
	serverMessage.getData().put("application","repeat");
	serverMessage.getData().put("status",result);
	websocketClient.sendMsg(serverMessage);  
}
```

I get these errors:
![image](https://cloud.githubusercontent.com/assets/2583367/14535213/03725f58-022a-11e6-97fb-7a6f39bf0dcd.png)

If I limit the record count to 1500, then I can send the message out without any problems. 
I don't know why Rhinoclient fails.

**Comment by mwambler** [comment] 2016-04-14 21:35
Need the full set of logs

On Thursday, April 14, 2016, Csaba Kiss <notifications@github.com> wrote:

> I am getting some new errors now. I am trying to build a big message from
> a view with 10000 records. Here is the server side code:
>
> function onOpen(){
>     print("we are open");
>     var db = session.getDatabase("","RepeatTest.nsf");
>     var usersView = db.getView("chats");
>     var documents = usersView.getAllEntries();
>     print("document length: " + documents.getCount());
>     var result = new java.util.HashMap();
>     var i=0;
>     var entry = documents.getFirstEntry();
>     while (entry != null)  {
>        var entryObject =new java.util.HashMap();
>        entryObject.put("author", entry.getDocument().getItemValueString("author"));
>        entryObject.put("chat", entry.getDocument().getItemValueString("chat"));
>     //   entryObject.put("created", entry.getDocument().getItemValueString("created"));
>        result.put(i.toString(), entryObject);
>        var tmpentry = documents.getNextEntry();
>        entry.recycle();
>        entry=tmpentry;
>        i++;
>     }
>     var serverMessage = websocketClient.createMessage();
>     serverMessage.setTo("broadcast"); //respond to everybody
>     serverMessage.setText("chat");
>     serverMessage.getData().put("application","repeat");
>     serverMessage.getData().put("status",result);
>     websocketClient.sendMsg(serverMessage);
> }
>
> I get these errors:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/14535213/03725f58-022a-11e6-97fb-7a6f39bf0dcd.png>
>
> If I limit the record count to 1500, then I can send the message out
> without any problems.
> I don't know why Rhinoclient fails.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/6#issuecomment-210030455>
>


-- 
Mark Ambler

**Comment by csakis** [comment] 2016-04-15 03:39
Here are the logs. There's not much more useful info in them.
[error-log-0[xml].txt](https://github.com/mwambler/xockets.io/files/220320/error-log-0.xml.txt)
[trace-log-0[xml].txt](https://github.com/mwambler/xockets.io/files/220321/trace-log-0.xml.txt)

**Comment by csakis** [comment] 2016-04-15 17:31
If I build a large string instead of a hashmap, then the script finishes without an error.

**Comment by mwambler** [comment] 2016-04-16 22:38
I noticed this in the log:  

javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: ReferenceError: "ex" is not defined

Do you have a variable "ex" defined anywhere in your script?

**Comment by csakis** [comment] 2016-04-16 22:42
No.

**Comment by mwambler** [comment] 2016-04-16 22:46
Add a try / catch around your domino operations.  See if anything is throwing it off in there (example below):

function onOpen(){
    print("we are open");
		
	try{
		var db = session.getDatabase("","RepeatTest.nsf");
		var usersView = db.getView("chats");
		var documents = usersView.getAllEntries();
		print("document length: " + documents.getCount());
		var result = new java.util.HashMap();
		var i=0;
		var entry = documents.getFirstEntry();
		while (entry != null)  {
		   var entryObject =new java.util.HashMap();
		   entryObject.put("author", entry.getDocument().getItemValueString("author"));
		   entryObject.put("chat", entry.getDocument().getItemValueString("chat"));
		//   entryObject.put("created", entry.getDocument().getItemValueString("created"));
		   result.put(i.toString(), entryObject);
		   var tmpentry = documents.getNextEntry();
		   entry.recycle();
		   entry=tmpentry;
		   i++;   
		}
	}catch(err){
		java.lang.System.println(err.message);
	}
    var serverMessage = websocketClient.createMessage();
    serverMessage.setTo("broadcast"); //respond to everybody
    serverMessage.setText("chat");
    serverMessage.getData().put("application","repeat");
    serverMessage.getData().put("status",result);
    websocketClient.sendMsg(serverMessage);  
}

**Comment by csakis** [comment] 2016-04-16 22:59
The errors occur outside of the try/catch loop when this line is executed:

`websocketClient.sendMsg(serverMessage); `

**Comment by mwambler** [comment] 2016-04-16 23:00
Wrap the whole script in try / catch, see if you get a better error message

On Saturday, April 16, 2016, Csaba Kiss <notifications@github.com> wrote:

> The errors occur outside of the try/catch loop when this line is executed:
>
> websocketClient.sendMsg(serverMessage);
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/6#issuecomment-210920919>
>


-- 
Mark Ambler

**Comment by csakis** [comment] 2016-04-16 23:06
no other meaningful error messages. Only these:
![image](https://cloud.githubusercontent.com/assets/2583367/14584138/8b006af6-03f5-11e6-921a-c91f07268b60.png)

Interestingly, the websocket OnError event is not fired at all.
Only the OnClose event

**Comment by mwambler** [comment] 2016-04-16 23:09
Can you send me the .nsf with data?

On Saturday, April 16, 2016, Csaba Kiss <notifications@github.com> wrote:

> no other meaningful error messages. Only these:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2583367/14584138/8b006af6-03f5-11e6-921a-c91f07268b60.png>
>
> Interestingly, the websocket OnError event is not fired at all.
> Only the OnClose event
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/6#issuecomment-210921345>
>


-- 
Mark Ambler

**Comment by csakis** [comment] 2016-04-16 23:12
Yes, I'll send a link to it in an email

**Comment by mwambler** [comment] 2016-04-17 00:01
Hi Csaba,
Took a look at your app.  I loaded the wsRepeat.xsp page and was able to repeat the problem (no pun intended :).  Seems you don't have a check for contains and are loading the listener over and over again in the beforePageLoad xpage event.  Below is the change that fixed the issue.  Don't depend on the onOpen event to send the data, move it to the onMessage event, and have a client side script execute after page load to invoke the listener...  onOpen should happen only once per listener's life cycle.

```javascript
var listener="/RepeatTest.nsf/applicationSSJS";
if(!websocketBean.containsSocketListener(listener)){
	websocketBean.addSocketEventListener("/RepeatTest.nsf","*",listener,"chatapp","password");
}
```

**Comment by csakis** [comment] 2016-04-17 00:30
I know I removed the listener check from the page, because it's a pain in the butt to edit the server side listener. I have to restart the http task manually to remove the active listener from the server.
I used the onOpen event because I wanted to send only a single message for a test, but I will modify it

**Comment by mwambler** [comment] 2016-04-17 00:33
reload-scripts is working on latest build

On Saturday, April 16, 2016, Csaba Kiss <notifications@github.com> wrote:

> I know I removed the listener check from the page, because it's a pain in
> the butt to edit the server side listener. I have to restart the http task
> manually to remove the active listener from the server.
> I used the onOpen event because I wanted to send only a single message for
> a test, but I will modify it
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwambler/xockets.io/issues/6#issuecomment-210928484>
>


-- 
Mark Ambler

**Comment by mwambler** [comment] 2016-04-18 21:17
Did adding contains check fix the problem ?

**Comment by mwambler** [comment] 2016-04-19 12:41
Closing this... make sure you do a check via contains for listeners...

var listener="/RepeatTest.nsf/applicationSSJS";
if(!websocketBean.containsSocketListener(listener)){
    websocketBean.addSocketEventListener("/RepeatTest.nsf","*",listener,"chatapp","password");
}

**Closed by mwambler** 2016-04-19 12:41 UTC
